--- 
about_content: |
     I am a technical support professional with a tenacity to solve problems using technology and automation. I have demonstrated a history of working in the primary/secondary education industry. I am skilled in hardware and software repair, system administration (OSX/iOS, Windows & Linux), Python, Java, C, C++, Scripting (Bash, BAT, Powershell, Google App Scripting). I am experienced in setting up development environments, network stacks, web servers,  MDM server, and client configurations. I also have experience in web development using: CMS, HTML, CSS, Javascript. Lastly, I have software development experience using OOP and MVC paradigms with the following software frameworks: JavaFX, Django, and .NET.
    
    I am most skilled in: <mark>Python</mark>, <mark>automation</mark> and  <mark>technical support</mark>.
about_profile_image: images/helloWorld.png
email: brian.d.pemberton@gmail.com
favicon: images/favicon.ico
footer_show_references: true
github_username: pemby
linkedin_username: brpemberton
more_content: |
    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
     - Eletronic Music Making
     - Gaming
     - Cooking
name: "Brian Pemberton"
plugins: 
  - jekyll-seo-tag
remote_theme: sproogen/resume-theme
repository: sproogen/resume-theme
sass: 
  sass_dir: _sass
  style: compressed
website: "https://pemby.github.io/"
