# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Brian Pemberton
test: Senior Network System Administrator
email: brian.d.pemberton@gmail.com
website: https://pemby.github.io/

# Social links
twitter_username: facespics
github_username:  pemby
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/helloWorld.png
about_content: | # this will include new lines to allow paragraphs
  I am a technical support professional with a tenacity to solve problems using technology and automation. I have demonstrated a history of working in the primary/secondary education industry. I am skilled in computer hardware and software repair, system administration (OSX/iOS, Windows & Linux). I am proficient in Python, Java, C, C++, Scripting (Bash, BAT, Powershell, Google App Scripting). I am experienced in setting up development environments, network stacks, and user environments in Windows, Linux, OSX. I am also experienced with setting up and configuring Linux network stacks (DNS, DHCP, and network accounts), configuring Apache web servers, and iOS MDM server and client configurations and setup. I am also experienced in web development using: HTML, CSS, Javascript. Sofware Development Experience using OOP, MVC, paradigms with the following software frameworks: JavaFX, Django, and .NET. 
  I am most skilled in: <mark>Python</mark>, <mark>automation</mark> and  <mark>technical support</mark>.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
