# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Brian Pemberton
test: Senior Network System Administrator
email: brian.d.pemberton@gmail.com
website: https://pemby.github.io/

# Social links
twitter_username: facespics
github_username:  pemby
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
#linkedin_username: jameswgrant
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brian and I am a technical support professional with tenacity to solve problems and automate solutions using technology. A demonstrated history of working in the primary/secondary education industry. Experience Skilled in Computer hardware and software repair, system administration (OSX, Windows & Linux). Proficient in programming Python, Java, C, C++, Scripting (Bash, BAT, Powershell, Google App Scripting), Experienced in setting up development environments, network stacks, and user environments in Linux, AWS, OSX, and Linux (Network accounts). Dev Ops, Linux network stacks, configuring LAMP, and Apache web servers.  Experienced in web development using: HTML, CSS, Javascript. Sofware Development Experience using OOP, MVC, paradigms with the following frameworks: JavaFX, Django, and .NET. 

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
